# Generated by Django 3.1.5 on 2022-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(default='', max_length=30)),
                ('login_name', models.CharField(default='', max_length=20, unique=True)),
                ('login_pwd', models.CharField(default='', max_length=32)),
                ('login_salt', models.CharField(default='', max_length=32)),
                ('status', models.IntegerField(default=1)),
                ('updated_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'login',
                'verbose_name_plural': 'login',
                'db_table': 'login',
                'managed': True,
            },
        ),
    ]
