# Generated by Django 3.1.5 on 2022-01-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
